from . import mail_message
from . import ir_actions_server
from . import res_company
from . import wa_message
from . import wa_mixin
from . import wa_account
from . import wa_compose
from . import wa_template
from . import wa_mass_send